# ~/.tmux_theme_vulcan.conf

# Status bar colors
set -g status-style bg="#ffffff",fg="#e7ddff"

# Pane border colors
set -g pane-border-style fg="#b042ff"
set -g pane-active-border-style fg="#b8ff12"

# Message/command line colors
set -g message-style bg="#b8ff12",fg="#000000",bold

# Left status (session name)
set -g status-left-length 40
set -g status-left "#[bg=#b8ff12,fg=#000000,bold] ⚡ #S #[bg=#b042ff,fg=#b8ff12] "

# Window status format
set -g window-status-format "#[fg=#000000] #I: #W "
set -g window-status-current-format "#[bg=#f24141, fg=#000000,bold] [ #I: #W ] "

# Right status (date and time)
set -g status-right "#[bg=#e7ddff, fg=#000000] %Y-%m-%d #[bg=#e7ddff, fg=#000000,bold] %H:%M "
