# ~/.dotfiles/distrobox.ini

[vulcan]
image=registry.fedoraproject.org/fedora:41
additional_flags="--env WORKSPACE_THEME=vulcan"
additional_packages="git fish tmux stow"
pre_init_hooks="printf 'install_weak_deps=False\nmax_parallel_downloads=10\n' >> /etc/dnf/dnf.conf"
init_hooks="curl -sSL https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz | tar -xz -C /usr/local/bin && chsh -s /usr/bin/fish"
replace=true

[mars]
image=registry.fedoraproject.org/fedora:41
additional_flags="--env WORKSPACE_THEME=mars"
additional_packages="git fish tmux stow nmap python3-pip"
pre_init_hooks="printf 'install_weak_deps=False\nmax_parallel_downloads=10\n' >> /etc/dnf/dnf.conf"
init_hooks="curl -sSL https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz | tar -xz -C /usr/local/bin && chsh -s /usr/bin/fish"
replace=true
