# ~/.config/starship_vulcan.toml

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[█](color_cyan)\
$os\
$username\
[](bg:color_mint fg:color_cyan)\
$directory\
[](fg:color_mint bg:color_red)\
$git_branch\
$git_status\
[](fg:color_red bg:color_teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_teal bg:color_base)\
$docker_context\
$conda\
[](fg:color_base bg:color_seafoam)\
$time\
[█ ](fg:color_seafoam)\
$line_break$character"""

palette = 'vulcan'

[palettes.vulcan]
color_base = '#1C2638'      # Darkest Navy
color_cyan = '#23495D'      # Deep Slate Cyan
color_teal = '#39707A'      # Muted Teal
color_seafoam = '#95E0CC'   # Bright Seafoam Green
color_mint = '#DAF2E9'      # Pale Ice Mint
color_crimson = '#9B222B'   # Dark Crimson
color_red = '#F14E52'       # Bright Coral Red

[os]
disabled = false
style = "bg:color_cyan fg:color_mint"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Kali = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_cyan fg:color_mint"
style_root = "bg:color_crimson fg:color_mint"
format = '[  $user ]($style)'

[directory]
style = "fg:color_base bg:color_mint"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_red"
format = '[[ $symbol $branch ](fg:color_mint bg:color_red)]($style)'

[git_status]
style = "bg:color_red"
format = '[[($all_status$ahead_behind )](fg:color_mint bg:color_red)]($style)'

[nodejs]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[c]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[rust]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[golang]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[php]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[java]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[kotlin]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[haskell]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_mint bg:color_teal)]($style)'

[python]
symbol = ""
style = "bg:color_teal"
format = '[[ ${symbol} (${version})( \($virtualenv\)) ](fg:color_mint bg:color_teal)]($style)'

[docker_context]
symbol = ""
style = "bg:color_base"
format = '[[ $symbol( $context) ](fg:color_seafoam bg:color_base)]($style)'

[conda]
style = "bg:color_base"
format = '[[ $symbol( $environment) ](fg:color_seafoam bg:color_base)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_seafoam"
format = '[[  $time ](fg:color_base bg:color_seafoam)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[▸](bold fg:color_seafoam)'
error_symbol = '[▸](bold fg:color_red)'
vimcmd_symbol = '[◂](bold fg:color_seafoam)'
vimcmd_replace_one_symbol = '[◂](bold fg:color_teal)'
vimcmd_replace_symbol = '[◂](bold fg:color_teal)'
vimcmd_visual_symbol = '[◂](bold fg:color_crimson)'
